In [35]:
import pandas as pd
import explanations
import glob, os

In [37]:
nehody = pd.df
for f in glob.glob(os.path.join('', "data/2018/*.csv")):
    print(f)

data/2018\00.csv
data/2018\01.csv
data/2018\02.csv
data/2018\03.csv
data/2018\04.csv
data/2018\05.csv
data/2018\06.csv
data/2018\07.csv
data/2018\08.csv
data/2018\09.csv
data/2018\10.csv
data/2018\11.csv
data/2018\12.csv
data/2018\13.csv
data/2018\14.csv
data/2018\15.csv
data/2018\16.csv
data/2018\17.csv
data/2018\18.csv
data/2018\19.csv
data/2018\CHODCI.csv

In [34]:
# data = pd.read_csv('data/2018/00.csv', sep=';', encoding='iso-8859-2', index_col=None, error_bad_lines=False)
nehody = pd.concat(map(lambda file: pd.read_csv(file, delim_whitespace=True), data_files))
nehody = pd.concat(map(pd.read_csv, (glob.glob(os.path.join('', "my_files*.csv")), sep=';', encoding='iso-8859-2', index_col=None, error_bad_lines=False)))

SyntaxError: invalid syntax (<ipython-input-34-d17ab889370b>, line 3)

In [30]:
data.columns = explanations.main_columns

In [31]:
data["druh_pozemni_komunikace"] = data["druh_pozemni_komunikace"].apply(lambda x: explanations.decode_key['druh_pozemni_komunikace'].get(x))

In [32]:
data.head()

,identifikacni_cislo,druh_pozemni_komunikace,cislo_pozemni_komunikace,den_mesic_rok,weekday(p2a),cas,druh_nehody,druh_srazky_jedoucich_vozidel,druh_pevne_prekazky,charakter_nehody,...,k,l,n,o,p,q,r,s,t,lokalita_nehody
0,2100180002,komunikace sledovaná; (ve vybraných městech),NaN,2018-01-01,1,50,3,0,2,2,...,sledovanákomunikace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2100180003,"komunikace účelová; ostatní (parkoviště, odpoč...",NaN,2018-01-01,1,40,4,0,0,1,...,místníkomunikace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2100180004,komunikace sledovaná; (ve vybraných městech),NaN,2018-01-01,1,114,1,4,0,2,...,sledovanákomunikace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,2100180005,komunikace místní,NaN,2018-01-01,1,232,3,0,4,1,...,místníkomunikace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2100180006,komunikace sledovaná; (ve vybraných městech),NaN,2018-01-01,1,230,5,0,0,2,...,místníkomunikace,NaN,3298196.0,NaN,Opačnýkesměruúseku,Pomalý,554782.0,507008.0,GN_V0.1UIR-ADR_410,1